### PR TITLE
fix #1490 TO:Server API create and update do not check network settings

### LINKED ISSUE #1490: TO: Server API create and update do not check network settings
[t.json.txt](https://github.com/Comcast/traffic_control/files/298511/t.json.txt)

Creating or editing a server using UI,  the ip address, gateway, and netmask must be consistent with each other or an error is raised and no change is made.   Same with ip6 address and gateway.

Using the api to create or update a server,  no such check is done,  and the server changes are made.  I created the attached json file and created a server:
```
curl -s ... -X POST -d '<json data>' http://localhost:3000/api/1.2/servers
```

Then in the UI, edit the new server and click Submit without making changes.  I got this error:
```
update():  10.10.10.220 and 111.222.111.1 are not in same network
Address ee80:1 is not a valid IPv6 address 
Gateway fe80:1 is not a valid IPv6 address 
ee80:1 and fe80:1 are not in same network
```

### PR DESCRIPTION
**Pull request by yorma**

### CODE REVIEW

**Comment by yorma** [comment]
fix issue https://github.com/Comcast/traffic_control/issues/1490
@dangogh

File: traffic_ops/app/lib/API/Server.pm [hunk 1]
```diff
@@ -393,75 +393,214 @@ sub details {
...
+    my $json        = shift;
+    my $update_base = shift;
+    my %params      = %{$json};
+    my $err         = undef;
+
+    if ( defined( $json->{'interface_mtu'} ) ) {
+        if ( $json->{'interface_mtu'} != '1500' && $json->{'interface_mtu'} != '9000' ) {
+            return ( \%params, "'interface_mtu' '$json->{'interface_mtu'}' not equal to 1500 or 9000!" );
+        }
+    }
```
Comment (dangogh) [inline traffic_ops/app/lib/API/Server.pm]: lots of indent changes..   Are you running perltidy with the recommended settings?
