### PR TITLE
Traffic Router no longer uses keystore for serving certificates for https delivery services

### LINKED ISSUE #1851: TR throws an error on startup when trying to download Geo Database
If the Geo Database already exists and TR is restarted, the following error is thrown in the log:  

> 2016-09-15 15:50:29,693 [FATAL] traffic_router.core.loc.AbstractServiceUpdater: [GeolocationDatabaseUpdater] Caught exception while attempting to download: https://trafops.kabletown.net/MaxMind/auto/GeoIP2-City.mmdb.gz
> java.net.SocketException: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
> 	at javax.net.ssl.DefaultSSLSocketFactory.throwException(SSLSocketFactory.java:248)
> 	at javax.net.ssl.DefaultSSLSocketFactory.createSocket(SSLSocketFactory.java:255)
> 	at sun.net.www.protocol.https.HttpsClient.createSocket(HttpsClient.java:409)
> 	at sun.net.NetworkClient.doConnect(NetworkClient.java:162)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
> 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
> 	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:275)
> 	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:371)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1104)
> 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:998)
> 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1512)
> 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1440)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.downloadDatabase(AbstractServiceUpdater.java:349)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.updateDatabase(AbstractServiceUpdater.java:130)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater$1.run(AbstractServiceUpdater.java:85)
> 	at java.lang.Thread.run(Thread.java:745)
> Caused by: java.security.NoSuchAlgorithmException: Error constructing implementation (algorithm: Default, provider: SunJSSE, class: sun.security.ssl.SSLContextImpl$DefaultSSLContext)
> 	at java.security.Provider$Service.newInstance(Provider.java:1617)
> 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
> 	at sun.security.jca.GetInstance.getInstance(GetInstance.java:164)
> 	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:156)
> 	at javax.net.ssl.SSLContext.getDefault(SSLContext.java:96)
> 	at javax.net.ssl.SSLSocketFactory.getDefault(SSLSocketFactory.java:122)
> 	at javax.net.ssl.HttpsURLConnection.getDefaultSSLSocketFactory(HttpsURLConnection.java:332)
> 	at javax.net.ssl.HttpsURLConnection.<init>(HttpsURLConnection.java:289)
> 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.<init>(HttpsURLConnectionImpl.java:85)
> 	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:62)
> 	at sun.net.www.protocol.https.Handler.openConnection(Handler.java:57)
> 	at java.net.URL.openConnection(URL.java:972)
> 	at com.comcast.cdn.traffic_control.traffic_router.core.loc.AbstractServiceUpdater.downloadDatabase(AbstractServiceUpdater.java:343)
> 	... 3 more
> Caused by: java.security.UnrecoverableKeyException: Password must not be null
> 	at sun.security.provider.JavaKeyStore.engineGetKey(JavaKeyStore.java:124)
> 	at sun.security.provider.JavaKeyStore$JKS.engineGetKey(JavaKeyStore.java:55)
> 	at java.security.KeyStore.getKey(KeyStore.java:1023)
> 	at sun.security.ssl.SunX509KeyManagerImpl.<init>(SunX509KeyManagerImpl.java:133)
> 	at sun.security.ssl.KeyManagerFactoryImpl$SunX509.engineInit(KeyManagerFactoryImpl.java:70)
> 	at javax.net.ssl.KeyManagerFactory.init(KeyManagerFactory.java:256)
> 	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.getDefaultKeyManager(SSLContextImpl.java:874)
> 	at sun.security.ssl.SSLContextImpl$DefaultSSLContext.<init>(SSLContextImpl.java:732)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
> 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
> 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
> 	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
> 	at java.security.Provider$Service.newInstance(Provider.java:1595)
> 	... 15 more

### PR DESCRIPTION
**Pull request by trevorackerman**
Fixes #1851

### CODE REVIEW

File: traffic_router/connector/src/main/java/com/comcast/cdn/traffic_control/traffic_router/protocol/LanguidProtocol.java [hunk 1]
```diff
@@ -51,7 +46,7 @@ public void init() throws Exception {
 	@Override
 	@SuppressWarnings("PMD.SignatureDeclareThrowsException")
 	public void start() throws Exception {
-		log.info("Start called; waiting for initialization to occur");
+		log.info("*************** Start called; waiting for initialization to occur");
```
Comment (trevorackerman) [inline traffic_router/connector/src/main/java/com/comcast/cdn/traffic_control/traffic_router/protocol/LanguidProtocol.java]: Nope
They can be removed without trouble.

File: traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java [hunk 2]
```diff
@@ -127,19 +145,50 @@ public boolean processConfig(final String jsonStr) throws JSONException, IOExcep
...
-						Thread.sleep(1000L);
+						publishStatusQueue.put(true);
 					} catch (InterruptedException e) {
-						LOGGER.warn("Interrupted while sleeping between checks of https certificates");
+						LOGGER.warn("Failed to notify certificates publisher we're waiting for certificates", e);
+					}
+
+					while (!cancelled.get() && !publishStatusQueue.isEmpty()) {
+						try {
+							LOGGER.info("Waiting for https certificates to support new config" + String.format("%x", publishStatusQueue.hashCode()));
```
Comment (dneuman64) [inline traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java]: Need a space after config

File: traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java [hunk 3]
```diff
@@ -96,22 +104,32 @@ public RegionalGeoUpdater getRegionalGeoUpdater() {
...
+	@SuppressWarnings({"PMD.CyclomaticComplexity", "PMD.NPathComplexity", "PMD.AvoidCatchingThrowable"})
 	public boolean processConfig(final String jsonStr) throws JSONException, IOException  {
+		isProcessing.set(true);
+		LOGGER.info("Entered processConfig");
 		if (jsonStr == null) {
 			trafficRouterManager.setCacheRegister(null);
+			cancelled.set(false);
+			isProcessing.set(false);
+			publishStatusQueue.clear();
 			return false;
```
Comment (dneuman64) [inline traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java]: Since we are logging when we enter Process config, I think we should put some logging here when we exit as well, otherwise the log will have "Enter processConfig" entries without associated exit ones.

File: traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java [hunk 4]
```diff
@@ -127,19 +145,50 @@ public boolean processConfig(final String jsonStr) throws JSONException, IOExcep
...
+							LOGGER.warn("Interrupted while waiting for status on publishing ssl certs", t);
+						}
 					}
 				}
 
+				if (cancelled.get()) {
+					cancelled.set(false);
+					isProcessing.set(false);
+					publishStatusQueue.clear();
+					return false;
```
Comment (dneuman64) [inline traffic_router/core/src/main/java/com/comcast/cdn/traffic_control/traffic_router/core/config/ConfigHandler.java]: We should put some logging here too.
